language: node_js
node_js:
  - lts/*

deploy:
  provider: heroku
  api_key:
    secure: CTNU1/WVDoZ0aUtrWKXRg5X4YQjuDROEqALYVsjqrdAW6SAZ2jS76S4MJ8i/wTXaiEKVMCKnMAv229+9DjeiRzEByd1WkDGCz+3/knRg3ZxwHegHWImWjTBDIXnjbGcBHmwAqEbNMSZU3lCf+WzoIce62pu8eqTBvrc37svD5KCfkVK8u4Fl/Ldq3Eu9/iaBeJnm1Y82Lh7rwUP4O+Wine2G3Pg0QFoE3RAL5yQBIw4l9e4OSjKQKlOmKCtzQGpfmP3hRaQGETdRdZX+colz5tgrfceqyTvcVhVqp3fh5oRSsPw5lLlvVy5usrT2fa7j0dRu/zUIDZm1kj5an6AN/sxZtT9ynguDTYJIV/Zb4DuVMd7sZlLRf88aap40GGnQGBcj/DhFZyVfhLE4mLJvQiU5KO4KRDa6KXLbHAUAiwn9n902Td8Spu/hqYzfgbtgz0S+aRQtvmltxI3FA1agNzsZqIcIlnkUEb4eSDye3A/J8WBXeXdrBZkNLRKC7HAQLTOwbMlJq0/1FzP887PM5UtY9DkcQjwWdNELXDHobqgzUu3CRfTMyjpjV1zF7/N+BDjT/IbFbwMHqjcR7RBXDRu7jDdZoXPV5SOrwQmfcp7z3EXr/d4zKgupdufDEiV+xk9ny2/tkdWwgY33j6/rQHO2k/99ukroAlGkriB/9SQ=
